/**
 * Bun HTTP Server for the flight-bun fixture.
 *
 * Consolidates the dual-server pattern (CDN/global.js + regional/region.js) from
 * the webpack and ESM flight fixtures into a SINGLE Bun-native server using
 * Bun.serve(). Handles RSC Flight streaming, SSR hydration, Server Actions,
 * static asset serving, and mock data — all in one file.
 *
 * Port: 3001 (configurable via PORT env var)
 * Runtime: Bun >= 1.1
 */

// React core — for createElement and use()
import * as React from 'react';

// Flight server APIs for RSC serialization and Server Action decoding.
// renderToReadableStream is aliased to avoid conflict with react-dom's version.
import {
  renderToReadableStream as renderFlightToReadableStream,
  decodeReply,
  decodeAction,
  decodeFormState,
} from 'react-server-dom-bun/server.browser';

// React DOM SSR — renderToPipeableStream for HTML generation with hydration.
import {renderToPipeableStream} from 'react-dom/server';

// Flight client — createFromReadableStream to consume Flight payload during SSR.
import {createFromReadableStream} from 'react-server-dom-bun/client.browser';

// Node.js stream utilities — bridge renderToPipeableStream output to web Response.
import {PassThrough, Readable} from 'node:stream';

// File system — read manifest files from the build directory.
import {readFile} from 'node:fs/promises';

// Path utilities — resolve file paths for static serving and manifests.
import {join, resolve} from 'node:path';

// ---------------------------------------------------------------------------
// Constants and Configuration
// ---------------------------------------------------------------------------

const PORT = parseInt(process.env.PORT || '3001', 10);

// __dirname equivalent for ESM in Bun.
const __dirname = new URL('.', import.meta.url).pathname;

// Root directory of the fixture (fixtures/flight-bun/).
const rootDir = resolve(__dirname, '..');

// Public assets directory (fixtures/flight-bun/public/).
const publicDir = resolve(rootDir, 'public');

// Build artifacts directory (fixtures/flight-bun/build/).
const buildDir = resolve(rootDir, 'build');

// ---------------------------------------------------------------------------
// Client Module Manifest Loading
// ---------------------------------------------------------------------------

// The client module manifest maps client component module IDs to their
// chunk/module information for Flight stream resolution. Generated by the
// build script (scripts/build.js).
let clientManifest = null;
try {
  const manifestPath = resolve(buildDir, 'react-client-manifest.json');
  const manifestContent = await readFile(manifestPath, 'utf8');
  clientManifest = JSON.parse(manifestContent);
} catch (e) {
  // Manifest may not exist on first run before build step completes.
  console.warn('Client manifest not found. Run `bun run build` first.');
  clientManifest = {};
}

// ---------------------------------------------------------------------------
// RSC Flight Rendering
// ---------------------------------------------------------------------------

/**
 * Renders the React Server Component tree into a Flight protocol ReadableStream.
 *
 * Mirrors the renderApp() pattern from fixtures/flight/server/region.js but
 * uses the web ReadableStream API (renderToReadableStream) instead of Node.js
 * pipe-based renderToPipeableStream.
 *
 * @param {*} returnValue - The return value from a Server Action invocation,
 *   included in the payload so the client can read it after re-rendering.
 * @param {*} formState - The form state from progressive enhancement flows,
 *   used by the client to reconcile form submissions that happened before
 *   JavaScript loaded.
 * @returns {ReadableStream} A web ReadableStream containing the Flight payload.
 */
async function renderApp(returnValue, formState) {
  // Dynamic import of the root Server Component.
  const m = await import('../src/App.js');
  const App = m.default;

  const root = React.createElement(App);

  // The payload includes the component tree, any Server Action return value,
  // and form state for progressive enhancement reconciliation.
  const payload = {root, returnValue, formState};

  // Serialize the payload into a Flight protocol ReadableStream using the
  // client module manifest for client reference resolution.
  const stream = renderFlightToReadableStream(payload, clientManifest);
  return stream;
}

// ---------------------------------------------------------------------------
// SSR HTML Rendering
// ---------------------------------------------------------------------------

/**
 * Converts an RSC Flight ReadableStream into a full SSR HTML Response.
 *
 * This function:
 * 1. Tees the Flight stream for parallel formState extraction and tree rendering.
 * 2. Extracts formState from the first copy for progressive enhancement support.
 * 3. Creates a Root component that lazily reads the second copy inside render.
 * 4. Uses renderToPipeableStream from react-dom/server for HTML generation.
 * 5. Bridges the Node.js pipe output to a web Response via PassThrough + Readable.toWeb().
 *
 * Mirrors the SSR flow from fixtures/flight/server/global.js lines 124-206 but
 * uses web ReadableStream.tee() instead of Node.js PassThrough.pipe() for
 * stream splitting, and createFromReadableStream instead of createFromNodeStream.
 *
 * @param {ReadableStream} flightStream - The Flight protocol stream to consume.
 * @returns {Promise<Response>} A web Response containing streaming SSR HTML.
 */
async function renderHTMLStream(flightStream) {
  // Tee the Flight stream — one copy for formState extraction, one for the
  // React tree rendering inside the Root component.
  const [stream1, stream2] = flightStream.tee();

  // Extract formState from the first copy of the stream. This is needed before
  // rendering starts so that renderToPipeableStream can reconcile progressive
  // enhancement form submissions.
  const formStateResult = await createFromReadableStream(stream1);
  const formState = formStateResult.formState;

  // Create a React component that lazily reads the RSC stream inside render.
  // This ensures Flight client preloads and module resolution happen during
  // the SSR render pass.
  let cachedResult;
  function Root() {
    if (!cachedResult) {
      // Read the second copy of the stream inside the render pass.
      cachedResult = createFromReadableStream(stream2);
    }
    return React.use(cachedResult).root;
  }

  // Resolve the bootstrap scripts for client-side hydration. These are the
  // entry point JS chunks that need to load in the browser for React to
  // hydrate the server-rendered HTML.
  let bootstrapScripts = [];
  try {
    const entrypointManifestPath = resolve(buildDir, 'entrypoint-manifest.json');
    const entrypointContent = await readFile(entrypointManifestPath, 'utf8');
    const entrypointManifest = JSON.parse(entrypointContent);
    bootstrapScripts = entrypointManifest.main?.js || ['/static/client.js'];
  } catch (e) {
    // Fall back to default bootstrap script path if manifest is unavailable.
    bootstrapScripts = ['/static/client.js'];
  }

  // Render the Root component to HTML using renderToPipeableStream from
  // react-dom/server. The pipe output is a Node.js Writable, so we bridge
  // it to a web Response through PassThrough + Readable.toWeb().
  return new Promise((resolvePromise, rejectPromise) => {
    const {pipe} = renderToPipeableStream(
      React.createElement(Root),
      {
        bootstrapScripts,
        formState,
        onShellReady() {
          // Create a PassThrough duplex stream and pipe the SSR HTML into it.
          const passthrough = new PassThrough();
          pipe(passthrough);
          // Convert the Node.js Readable side to a web ReadableStream.
          const webStream = Readable.toWeb(passthrough);
          resolvePromise(
            new Response(webStream, {
              headers: {'Content-Type': 'text/html'},
            })
          );
        },
        onShellError(error) {
          // If the shell fails to render, reject the promise so the caller
          // can return a 500 error response.
          rejectPromise(error);
        },
      }
    );
  });
}

// ---------------------------------------------------------------------------
// Server Action Handler
// ---------------------------------------------------------------------------

/**
 * Processes POST requests for Server Actions.
 *
 * Handles two branches:
 * 1. Client-invoked Server Actions (with rsc-action header): The client sends
 *    the server reference ID and encoded arguments. We decode, call the action,
 *    and re-render the app with the return value.
 * 2. Progressive enhancement (no rsc-action header): A form submission that
 *    happened without JavaScript. We decode the FormData, call the action,
 *    and re-render with formState for reconciliation.
 *
 * Mirrors fixtures/flight/server/region.js lines 203-260 but uses Bun's native
 * Request.formData() instead of busboy for multipart parsing.
 *
 * @param {Request} req - The incoming web Request object from Bun.serve().
 * @returns {Promise<Response>} A web Response containing the re-rendered Flight stream.
 */
async function handleServerAction(req) {
  const serverReference = req.headers.get('rsc-action');

  if (serverReference) {
    // Client-side invoked Server Action.
    // The rsc-action header contains "filepath#exportName".
    const [filepath, name] = serverReference.split('#');
    const action = (await import(filepath))[name];

    // Validate that this is actually a function we intended to expose and
    // not the client trying to invoke arbitrary functions. In a real app,
    // you'd have a manifest verifying this before even importing it.
    if (action.$$typeof !== Symbol.for('react.server.reference')) {
      throw new Error('Invalid action');
    }

    // Decode the action arguments from the request body.
    let args;
    const contentType = req.headers.get('content-type') || '';
    if (contentType.startsWith('multipart/form-data')) {
      // For multipart form data, parse via Bun's native Request.formData().
      const formData = await req.formData();
      args = await decodeReply(formData);
    } else {
      // For text-encoded bodies, decode from the raw text.
      const body = await req.text();
      args = await decodeReply(body);
    }

    // Invoke the action with the decoded arguments.
    const result = action.apply(null, args);
    try {
      // Wait for any mutations to settle.
      await result;
    } catch (x) {
      // We handle the error on the client side.
    }

    // Re-render the app with the action's return value so the client
    // can read the updated tree and the action result.
    const flightStream = await renderApp(result, null);
    return new Response(flightStream, {
      headers: {'Content-Type': 'text/x-component'},
    });
  } else {
    // Progressive enhancement — form submission without JavaScript.
    // The form data contains encoded action references that decodeAction
    // can extract and resolve.
    const formData = await req.formData();
    const action = await decodeAction(formData);
    try {
      // Call the decoded action and capture the result.
      const result = await action();
      // Decode form state for progressive enhancement reconciliation.
      const formState = decodeFormState(result, formData);
      // Re-render with the formState so the client can reconcile.
      const flightStream = await renderApp(null, formState);
      return new Response(flightStream, {
        headers: {'Content-Type': 'text/x-component'},
      });
    } catch (x) {
      // On error, re-render without formState.
      const flightStream = await renderApp(null, null);
      return new Response(flightStream, {
        headers: {'Content-Type': 'text/x-component'},
      });
    }
  }
}

// ---------------------------------------------------------------------------
// Static File Serving
// ---------------------------------------------------------------------------

/**
 * Serves a static file using Bun's native Bun.file() API.
 *
 * Bun.file() returns a BunFile that can be passed directly to Response().
 * Content-Type is automatically detected based on file extension, and large
 * files are streamed efficiently.
 *
 * @param {string} filePath - Absolute path to the file to serve.
 * @returns {Promise<Response|null>} A Response with the file contents, or null
 *   if the file does not exist.
 */
async function serveStaticFile(filePath) {
  try {
    const file = Bun.file(filePath);
    const exists = await file.exists();
    if (!exists) {
      return null;
    }
    return new Response(file);
  } catch (e) {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Main Server
// ---------------------------------------------------------------------------

const server = Bun.serve({
  port: PORT,

  /**
   * Main request handler for the Bun HTTP server.
   *
   * Routes:
   * - POST /         → Server Actions (rsc-action header or progressive enhancement)
   * - GET  /todos    → Mock JSON data endpoint
   * - GET  /public/* → Static assets from the public/ directory
   * - GET  /favicon.ico → Favicon from public/
   * - GET  /static/* → Client build artifacts from the build/ directory
   * - GET  /         → SSR HTML (Accept: text/html) or Flight stream (otherwise)
   * - *              → 404 Not Found
   */
  async fetch(req) {
    const url = new URL(req.url);
    const pathname = url.pathname;

    // -----------------------------------------------------------------------
    // POST / — Server Actions
    // -----------------------------------------------------------------------
    if (req.method === 'POST' && pathname === '/') {
      try {
        return await handleServerAction(req);
      } catch (e) {
        console.error('Server Action error:', e);
        return new Response('Internal Server Error', {status: 500});
      }
    }

    // -----------------------------------------------------------------------
    // GET /todos — Mock data endpoint
    // -----------------------------------------------------------------------
    if (pathname === '/todos') {
      return Response.json([
        {id: 1, text: 'Shave yaks'},
        {id: 2, text: 'Eat kale'},
      ]);
    }

    // -----------------------------------------------------------------------
    // Static assets from public/ directory
    // -----------------------------------------------------------------------
    if (pathname.startsWith('/public/') || pathname === '/favicon.ico') {
      const filePath =
        pathname === '/favicon.ico'
          ? join(publicDir, 'favicon.ico')
          : join(publicDir, pathname.slice('/public/'.length));
      const response = await serveStaticFile(filePath);
      if (response) {
        return response;
      }
    }

    // -----------------------------------------------------------------------
    // Client build artifacts from build/ directory
    // -----------------------------------------------------------------------
    if (pathname.startsWith('/static/')) {
      const filePath = join(buildDir, pathname.slice('/static/'.length));
      const response = await serveStaticFile(filePath);
      if (response) {
        return response;
      }
    }

    // -----------------------------------------------------------------------
    // Main page — SSR HTML or Flight stream based on Accept header
    // -----------------------------------------------------------------------
    if (pathname === '/' || pathname === '/index.html') {
      try {
        const accept = req.headers.get('accept') || '';

        if (
          accept.includes('text/x-component') ||
          !accept.includes('text/html')
        ) {
          // RSC Flight payload request — return the Flight stream directly.
          // This is used by client-side navigations where the React client
          // fetches updated component trees without a full page reload.
          const flightStream = await renderApp(null, null);
          return new Response(flightStream, {
            headers: {'Content-Type': 'text/x-component'},
          });
        } else {
          // HTML request — perform full SSR with embedded Flight data.
          // This is the initial page load path where the server renders
          // HTML for fast first paint and embeds the Flight payload for
          // client-side hydration.
          const flightStream = await renderApp(null, null);
          return await renderHTMLStream(flightStream);
        }
      } catch (e) {
        console.error('Render error:', e);
        return new Response('Internal Server Error', {status: 500});
      }
    }

    // -----------------------------------------------------------------------
    // 404 — Not Found
    // -----------------------------------------------------------------------
    return new Response('Not Found', {status: 404});
  },
});

console.log(
  `Flight Bun Server listening on http://localhost:${server.port}...`
);
